### ISSUE TITLE
Tragam suas dúvidas!

### ISSUE THREAD

**Issue by Cinema-Etim** [Cinema-Etim/Cinema#1]
Por favor, nos avisem caso tenham dúvidas! Estamos aqui para ajudá-los 😃

**Comment by bmarchete** [comment]
Essa issue não tem sentido, @Cinema-Etim pode fechar ela!

**Comment by Cinema-Etim** [comment]
Fiz essa pra eles comentarem algo logo, era a toa mesmo... @bmarchete
