### ISSUE TITLE
Muitos problemas com o banco de dados

### ISSUE THREAD

**Issue by CaioLemes** [Cinema-Etim/Cinema#4]
Gente , é quase impossivel resolver essas questão por erros que tem no banco de dados e vou explicar

-Na tabela filme vocês colocaram 'duracao' como varchar e na questão 1 pede a media , mas não tem como fazer media de '80 min ' e '90 min' já que tem texto no meio.

-Não existe N para N de Filme para Diretor  , Filme só pode ter 1 diretor não N diretores 

-Não há necessidade de criar uma tabela para genero ,poderia ter colocado como um atributo em Filmes ,e muito menos uma tabela filho 

-Também não há necessidade de criar tabela para critica ,pois só tem 1 atributo .

-O atributo dataestreia estão todos como '0000-00-00' , basicamente as questões que tem uma data especifica assim como a questão 1 é praticamente nulo.

Olha , eu estou fazendo todas as questões com os comandos que acredito a sintaxe estar correto ,mas muitas vezes nem vai aparecer nada porque o banco de dados está com defeito e muito incoerente com as informações postas e com o que as questões pedem.

**Comment by Cinema-Etim** [comment]
A questão 1 foi muito bem posta,vamos rever aqui na central.
 A questão dos diretores é por conta de um filme poder ter mais de um diretor ajudando. Vamos supor em uma peça de teatro, há peças em que precisa-se de muitos figurantes, como uma plateia, uma situação programada, então para que consigam ensaiar todos as partes da peça a mesma é separada e depois de pronta ensaiada junta, nessa separação cada diretor dirige uma equipe, o mesmo pode acontecer em grandes filmes.
A questão do gênero realmente poderia ser da forma descrita, mas como visto nas aulas de TLBD que acredito que você tenha assistido conosco ano passado, quando você repete muito algo (ex: Sabão em pó: Marca X, Amaciante: Marca X), é mais prático você criar uma tabela a parte com isso escrito e numerá-las para evitar ficar digitando 500x a mesma coisa, na tabela que criamos tem poucos filmes, mas na realidade existem milhares de filmes, alguns gêneros se repetiram diversas vezes. 
A questão da crítica é algo que você tem que pensar conosco, ninguém tem o mesmo pensamento perante uma coisa, logo, é impossível que um filme tenha a mesma crítica de todos os expectadores.Vamos imaginar um site que podemos assistir filmes, muitos usuários podem assistir e avaliar, muitos reclamam da definição do vídeo que foi postado, mas alguns postam realmente sobre o filme, e nesses que postam sobre o filme há muitas avaliações e justificativas diferentes. Foi nessa linha de raciocínio que criamos a nossa. 
A última questão vamos verificar e daremos um retorno assim que solucionarmos. 
Pedimos desculpas pelo transtorno! Logo traremos novas versões do banco de dados para que você consiga realizar as atividades. Tenha uma boa tarde!

**Comment by Cinema-Etim** [comment]
Fizemos umas correções para melhor resultado. Por favor, qualquer coisa nos avise novamente! Obrigada!! 👍
