### ISSUE TITLE
Questão 5 ?

### ISSUE THREAD

**Issue by CaioLemes** [Cinema-Etim/Cinema#7]
Não entendi a questão

Todos os orçamentos foi para 80.000.000 ,mas como vou reorganizar sendo que eu não tenho os valores antigos

**Comment by Cinema-Etim** [comment]
É o seguinte -> muitos filmes que tiveram orçamento de 80.000.000 foram para valores superiores, então todos de valor maior na realidade são 80.000.000 ^-^ Consegui esclarecer?

**Comment by CaioLemes** [comment]
update filmes
set orcamento = 80000000
where orcamento > 80000000;

**Comment by Cinema-Etim** [comment]
Parabéns, sua questão está correta!
